server:
  port: 8080
spring:
  application:
    name: push-rest-service

springdoc:
  swagger-ui:
    use-root-path: true
  show-actuator: true

management:
   security:
      enabled: false
   endpoints:
     web:
       exposure:
         include: "*"

vapid:
  subject: mailto:admin@override.com
